server.port=8084
spring.application.name=axhub-tool-other

spring.profiles.active=local

# Suppress Kafka Connection Logs
logging.level.org.apache.kafka=ERROR

# MCP Function Register overrides
mcp.functions.get_template_file_url.register=true
