spring.application.name=axhub-admin
server.port=8081

# 기본적으로 local 환경을 실행
spring.profiles.active=local

# MyBatis 공통 설정
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=
mybatis.configuration.map-underscore-to-camel-case=true
spring.sql.init.mode=always

logging.level.com.corundumstudio.socketio=DEBUG