spring.application.name=axhub-admin

# application.properties (?? ??, Redis ? ??)
server.port=8080

spring.datasource.url=jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;
spring.datasource.driverClassName=com.p6spy.engine.spy.P6SpyDriver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=
spring.sql.init.mode=always

mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.corundumstudio.socketio=DEBUG