plugins {
    id 'java-library'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    
    api 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    api 'io.github.resilience4j:resilience4j-core:2.2.0'
    api 'io.github.resilience4j:resilience4j-circuitbreaker:2.2.0'
    api 'io.github.resilience4j:resilience4j-ratelimiter'
    api 'io.github.resilience4j:resilience4j-retry:2.2.0'
    api 'org.springframework.boot:spring-boot-starter-aop:3.3.0'

    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    api 'com.h2database:h2'
    api 'p6spy:p6spy:3.9.1'
    api 'io.lettuce:lettuce-core:6.6.0.RELEASE'

    api "org.mapstruct:mapstruct:1.5.5.Final"
    
    api 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.1'
    api 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    api 'com.networknt:json-schema-validator:1.4.0'
    api 'org.springframework.kafka:spring-kafka:3.2.0'
    api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok:1.18.32'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
}
