# Render ?´ë¼?°ë“œ ?˜ê²½ ?„ìš© ?¤ì •
server.port=${PORT:8085}
axhub.gateway.url=https://axhub-gateway.onrender.com
axhub.tool.url=https://dap-tool-payment.onrender.com

# EIMS ?™ì  ?¼ìš°???‘ì† ?•ë³´ (Mock)
eims.http.url=http://localhost:${server.port}/api/gateway
eims.tcp.host=127.0.0.1
eims.tcp.port=8090
eims.tcp.timeout=5000
eims.jsp.form.url=http://localhost:${server.port}/mock/jsp-form
eims.jsp.json.url=http://localhost:${server.port}/mock/jsp-json
eims.mci.url=http://localhost:${server.port}/api/mock/esb/api
eims.mcistring.url=http://localhost:${server.port}/api/mock/esb/string

# --- ? í•œ?¼ì´??EAI/MCI ?°ê³„ IP ?•ë³´ (ê°œë°œ ?˜ê²½) ---
shinhan.integration.envrTypeCd=D
shinhan.integration.eai.url=http://10.176.32.181
shinhan.integration.internalMci.url=http://10.176.32.173
shinhan.integration.bancaMci.url=http://10.176.32.117
shinhan.integration.externalMci.url=http://10.176.32.176
