server.port=8082
spring.application.name=axhub-tool-sms

spring.profiles.active=local

# Suppress Kafka Connection Logs
logging.level.org.apache.kafka=ERROR

# Auto Prefix Namespace
mcp.namespace=sms
