spring:
  config:
    import: "classpath:config/application-glow-local.yml"

mcp:
  functions:
    send_email:
      description: "이메일 발송"
      prompt: "고객에게 이메일을 발송해줘."
      mappingId: "EMAIL_SEND_001"
