server.port=8083
spring.application.name=axhub-tool-email

spring.profiles.active=local

# Suppress Kafka Connection Logs
logging.level.org.apache.kafka=ERROR

# Auto Prefix Namespace
mcp.namespace=email

# API 보안 키 설정
mcp.security.tenant-domains.TESTER-DEV=ALL
