# Glow 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod

glow:
  communication:
    common:
      env-type: P
    mci:
      host: ${GLOW_COMMUNICATION_MCI_HOST}
      port: ${GLOW_COMMUNICATION_MCI_PORT}
    extmci:
      host: ${GLOW_COMMUNICATION_EXTMCI_HOST}
      port: ${GLOW_COMMUNICATION_EXTMCI_PORT}
    eai:
      host: ${GLOW_COMMUNICATION_EAI_HOST}
      port: ${GLOW_COMMUNICATION_EAI_PORT}