# Render ?\uFFFD\uB77C?\uFFFD\uB4DC ?\uFFFD\uACBD ?\uFFFD\uC6A9 ?\uFFFD\uC815
server.port=${PORT:8083}
axhub.gateway.url=https://axhub-gateway.onrender.com
axhub.tool.url=https://axhub-tool-sms.onrender.com

# EIMS ?\uFFFD\uC801 ?\uFFFD\uC6B0???\uFFFD\uC18D ?\uFFFD\uBCF4 (Mock)
eims.http.url=http://localhost:${server.port}/api/gateway
eims.tcp.host=127.0.0.1
eims.tcp.port=8090
eims.tcp.timeout=5000
eims.jsp.form.url=http://localhost:${server.port}/mock/jsp-form
eims.jsp.json.url=http://localhost:${server.port}/mock/jsp-json
eims.mci.url=http://localhost:${server.port}/api/mock/esb/api
eims.mcistring.url=http://localhost:${server.port}/api/mock/esb/string

# --- ?\uFFFD\uD55C?\uFFFD\uC774??EAI/MCI ?\uFFFD\uACC4 IP ?\uFFFD\uBCF4 (\uAC1C\uBC1C ?\uFFFD\uACBD) ---
shinhan.integration.envrTypeCd=D
shinhan.integration.eai.url=http://10.176.32.181
shinhan.integration.internalMci.url=http://10.176.32.173
shinhan.integration.bancaMci.url=http://10.176.32.117
shinhan.integration.externalMci.url=http://10.176.32.176
